local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/vshandy2/script/main/xheptcofficial%20gitbook.lua"))()
local troll = Library.CreateLib("troll", "Ocean")
local troll = troll:NewTab("TabName")
local troll1 = troll:NewSection("Section Name")
troll1:NewButton("1", "invisble", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/vshandy2/script/main/troll/troll.lua", true))()
end)
troll1:NewButton("2", "Pet Simulator | by Rafa", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/vshandy2/script/main/troll/troll2.lua", true))()
end)
troll1:NewButton("3", "fthax", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/vshandy2/script/main/troll/troll3.lua"))()
end)